import { Outfit } from 'next/font/google';
import './globals.css';
import Nav from './components/Nav';
import Footer from './components/Footer';

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Altrisia',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased max-w-7xl mx-auto px-4`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}